DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS gap;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE gap (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  isClose TEXT NOT NULL,
  dateSelected TEXT UNIQUE NOT NULL
);